common: &common
  adapter: postgresql
  username: Jason
  password: pouvoir1! # from psql setup, see Postgresql
  host: localhost
  encoding: utf8
  pool: 5


development:
  <<: *common
  database: blog_development

test:
  <<: *common
  database: blog_test

production:
  <<: *common
  database: blog_production